<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/11/17
 * Time: 13:36
 */


/**
 * 1.定义抽象类的关键字是abstract
 * 2.抽象类中的抽象方法只定义不需要实现，普通方法可以实现
 * 3.普通类中不能写抽象方法
 * 4.抽象类可以写普通方法和抽象方法
 * 5.抽象类不能实例化
 */
   abstract  class Animal{

       public function run(){
           echo "动物都可以跑";
       }

       abstract function sleep();
       abstract function jump();
   }

   abstract class mysql{

       public function connect(){
//           mysqli_connect();
       }

       abstract function insert();
       abstract function  select();
       abstract  function delete();
       abstract function update();
   }

//     $db = new mysql();

   class demo extends mysql{

    public function connect()
    {
        parent::connect(); // TODO: Change the autogenerated stub
    }
    public function delete()
    {
        // TODO: Implement delete() method.
    }
    public function insert()
    {
        // TODO: Implement insert() method.
    }
    public function select()
    {
        // TODO: Implement select() method.
    }
    public function update()
    {
        // TODO: Implement update() method.
    }
}
   $demo1 = new demo();


   class cat extends Animal {

        public function run()
        {
            parent::run(); // TODO: Change the autogenerated stub
        }
        public function sleep()
        {
            // TODO: Implement sleep() method.
        }

        public function jump()
        {
            // TODO: Implement jump() method.
        }

   }
//
//   $cat = new cat();
//   $cat->run();